### PR TITLE
Fix issues with the manifest section.

### PR DESCRIPTION
**Pull request by franciscoRdiaz**
- Modify docker-compose (remove container names, ports, networks..)
- Modify the endpoints name and content.

### CODE REVIEW

**Comment by varungowtham** [comment]
Hi, 
Clarifying, if you would need any changes in the provided docker-compose file?

**Comment by franciscoRdiaz** [comment]
Hi,
Yes. You must change the file docker-compose.

The definition of services can not have:
- Port Section since they can not bind ports on the host.
- The name of the containers.
- Own networks. They must use the Elastest network ('elastest_elastest' network.)
- Its own ip for each service.

An example of docker-compose is inside the json file. Tell me any doubt you have.

Regards.

**Comment by franciscoRdiaz** [comment]
Another thing,

Already we can create the eds services through ESM whit the json file that I sent you, but  we dont have acces to the gui (http://localhost:6065/static/eds.html or http://localhost:8080/eds/ui/)

Could you help us build the docker-compose correctly?

Thanks.

**Comment by varungowtham** [comment]
Understood. The docker-compose file will be changed as required. 
Regarding the previous comment about GUI, you are not able to access because:
- Ports 8080 and 6065 are not bound to the localhost in docker-compose.
- The frontend service acts like a gateway and zigbeeipe, memsipe services use the frontend's IP address given in the docker-compose to connect with it. This has been hard coded internally in EDS. Currently there are no IP addresses assigned to the services. For this reason (http://localhost:6065/static/eds.html) will not be available even if port 6065 is bound to a host port. This is related to networking of the containers. 
- The (http://localhost:8080/eds/ui/) should be available if you could bind the 8080 port to a host port. 

 I will try to solve the issue. Can you please let me know, if not for bound host ports, how are you planning to access the service?

**Comment by micaelgallego** [comment]
Hi Varun,

In ElasTest it is possible to start several instances of the same Test
Support Service. For that reason, it is not possible to bind ports in the
host to avoid collisions with the second instance. Other restrictions like
container name or fixing IPs are due to same reason.

To access to the graphical interface it is possible to use the container IP
directly, without binding to port to localhost.

Regarding to fixed IPs, it is possible to use the name of the service as
DNS name of the container as explained here
https://docs.docker.com/compose/networking/

Regarding to the network to be used, we have to check if it is mandatory to
use "elastest_elastest" network or other can be used. At the moment, we
will use "elastest_elastest" as Paco sugest and see if there are any
problem with that.




El 29 sept. 2017 1:30 p. m., "varungowtham" <notifications@github.com>
escribió:

Understood. The docker-compose file will be changed as required.
Regarding the previous comment about GUI, you are not able to access
because:

   - Ports 8080 and 6065 are not bound to the localhost in docker-compose.
   - The frontend service acts like a gateway and zigbeeipe, memsipe
   services use the frontend's IP address given in the docker-compose to
   connect with it. This has been hard coded internally in EDS. Currently
   there are no IP addresses assigned to the services. For this reason (
   http://localhost:6065/static/eds.html
   <http://localhost:6065/static/eds.html>) will not be available even if
   port 6065 is bound to a host port. This is related to networking of the
   containers.
   - The (http://localhost:8080/eds/ui/) should be available if you could
   bind the 8080 port to a host port.

I will try to solve the issue. Can you please let me know, if not for bound
host ports, how are you planning to access the service?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/elastest/elastest-device-emulator-service/pull/76#issuecomment-333102320>,
or mute the thread

**Comment by varungowtham** [comment]
Hi Mica, 
Thank you for informing about this, it was helpful. I will try to solve the issues that Francisco has pointed. 
The DNS approach is new feature for OpenMTC that EDS uses. I will try to address this asap.

**Comment by micaelgallego** [comment]
Thank you very much Varun.

**Comment by varungowtham** [comment]
Hi Mica, Hi Francisco,
The solution was straight forward and simple! I have copied the manifest entry in elastestservice.json to docker-compose file and made necessary changes.

It should be possible to access the GUI using: 
* http://<frontend_IP>:6065/static/eds.html
* http://<api_IP>:8080/eds/ui

Best,
Varun

**Comment by micaelgallego** [comment]
Thank you Varun. We will test it on monday.

**Pull request merged**
